const express = require("express");
const router = express.Router();
const viewController = require("../controller/viewController");
const authContoller = require("../controller/authContoller");
const cartController = require("../controller/cartController");
router.use(authContoller.isLoggedin);
router.route("/adminlogin").get(viewController.adminLoginForm);
router.route("/userlogin").get(viewController.userLoginForm);
router.route("/signup").get(viewController.userSignupForm);
router.route("/overview").get(viewController.overview);
router.route("/activate/:token").get(viewController.acctivated);
router.route("/notify").get(viewController.notify);
router.route("/adminOverview").get(viewController.AdminOverview);
router.route("/postfood").get(viewController.postfood);
router.route("/getfood").get(viewController.getAllfood);
router.route("/getusers").get(viewController.getUsers);
router.route("/viewCart").get(cartController.total, viewController.viewcart);
router.route("/viewcancel").get(viewController.viewcancel);
module.exports = router;
